name: snippet_score
on: [push, pull_request, workflow_dispatch]
env:
    # Setting an environment variable with the value of a configuration variable
    SNIPPET_SCORE: ${{vars.SNIPPET_SCORE}}
    GH_TOKEN_VARS: ${{secrets.GH_TOKEN_VARS}}            

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Replace with the Python version you're using
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Replace with the name of your requirements file
    # - name: pytest - excluding the snippets
    #   run: |
    #     pytest -m 'not snippets'

    - name: test the snippets
      continue-on-error: true
      run: |
        pytest -m 'snippets'
    - name: compare and update
      run: |
        python .github/workflows/compare_score.py
